spring.application.name=tiie-service

# ===============================
# DATABASE CONFIG (Cloud SQL)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

# ===============================
# SERVER (Cloud Run)
# ===============================
server.port=${PORT:8080}

# ===============================
# JWT
# ===============================
security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.expiration=3600000